/**
 * The Shattered City — Chapter One: The Hydraulic Press.
 *
 * Manuscript as supplied by the author. One string per paragraph.
 */

export const chapterOne = {
  label: "Chapter One",
  title: "The Hydraulic Press",
  location: "NEO-TETHYS · LOWER SECTORS",
  epigraph: {
    text: "Pressure is mercy.",
    attribution: "Lower-sector valve-house maxim",
  },
  paragraphs: [
    "Darkness did not fall in Neo-Tethys. It came down like a hydraulic press.",
    "Sophia woke with concrete flexing under her spine.",
    "For one suspended second, she could not place the wrongness. The transit platform had always had a pulse: cable tension in the soles of her boots, turbine vibration in the metal rail, the faint tremor of ten thousand people moving somewhere above and below. The pulse was gone. In its place was a silence so complete that her own breath sounded borrowed.",
    "Then something far beneath the wreckage gave way.",
    "The deck listed beneath her. Dust sifted into her mouth.",
    "Sophia rolled before the next piece of ceiling came down, driving her shoulder into a grid of torn metal. Pain went bright across her ribs. She waited for the worse pain—the one that would tell her something had broken.",
    "It did not come from her ribs.",
    "It came from her right arm.",
    "The old brown mark along her inner forearm had opened into lines of amber light. They ran in a narrow geometry from wrist to elbow, too exact to be a burn and too hot to be anything else. The heat had a rhythm. Not a heartbeat, exactly. A demand. Move.",
    "Sophia clenched her hand until her nails cut crescents into her palm.",
    "“Kiera?” Her voice scraped in the dust. “Zoey?”",
    "A cough answered from her left. Not a weak one. A deliberate one, followed by the scrape of a boot testing the platform.",
    "“I’m here,” Kiera said. “Do not move quickly.”",
    "The relief hit Sophia hard enough to make her angry. “Where are you?”",
    "“Three meters left of you. There’s a fracture between us. The primary cables snapped, but the secondary arrestors caught part of the drop.” Kiera’s voice was thin with pain and still aggravatingly composed. “We fell at least forty meters. Possibly fifty. The platform is holding on two points.”",
    "Sophia found her by the sound, crawling over broken panels with one hand. The emergency strips had failed. A distant maintenance lamp blinked once every few seconds, giving her a sequence of still images: torn cable, fractured rail, Kiera’s pale face emerging from grey powder.",
    "Kiera sat with her back braced to a tilted handrail, one trouser leg dark with blood at the knee. A blue lattice shimmered beneath the skin at her collarbone. She had one hand pressed over it, trying to quiet it.",
    "“You’re hurt.” Sophia reached for her.",
    "“Not enough to make you touch it.” Kiera caught Sophia’s wrist before she could pull fabric aside. Her fingers were cold. Her eyes stopped on the amber light in Sophia’s arm. “That was dormant yesterday.”",
    "“So was yours.”",
    "“Yes.”",
    "That single word held too much. Fear. Decision. A conclusion neither of them had enough information to name.",
    "The morning returned in pieces whenever her hands had nothing to hold.",
    "Roll call on the work deck at shift change. The foreman reading names off a slate without looking up. Kiera’s name called, and Sophia’s own mouth opening first, as it had every morning for two years, to make the trade: Sophia takes the cable line, Kiera takes the meter desk. Kiera’s lungs had been pulling wet all week, and the foreman would have moved her to the pumps if he’d noticed, and the pumps were where wet lungs drowned you slowly in front of a quota board. It was faster to decide than to explain. Kiera had stood behind her saying nothing, and afterwards, in the corridor, she had said, “You could have let me answer.” And Sophia had said, “You would have taken the pumps.” Which was true. Which ended the argument. It left a hairline crack in a strut, the kind you pass a hundred load tests and never think about until the hundred-and-first.",
    "Their mother had done it differently. Zoey had spilled hot water once, eight years ago, and Elena had knelt in the spill and held the scalded hand under the tap and asked—not instructed, asked—do you want the burn jelly, or just the cold? Zoey had chosen the cold. Elena had given her the cold, and Zoey had been brave about it all evening, proud as a stoker.",
    "Sophia had been twelve. She had watched from the doorway with something like resentment. Why ask? Asking wasted time. Asking let them choose wrong.",
    "Later—after their mother stopped coming home, after the shifts started, after Kiera’s cough came back every winter like a debt collector—Sophia had stopped noticing when deciding for them stopped being an emergency measure. It had become a habit. Then a skill. Then a fact about her, like the wrench on her belt.",
    "Now, on a listing deck with Kiera’s blood drying black at the knee and amber light crawling her own arm, Sophia surveyed the damage the way her mother used to survey a failing pump: what could be held, what could be rerouted, what would simply have to run hot until it burned out.",
    "She did not ask either of them what they wanted. There had not been time to ask, and there had never been time to ask, and the fact that those two sentences had become indistinguishable did not occur to her.",
    "“Zoey.” Sophia turned, louder now. “Answer me.”",
    "A small sound came from the underside of a fallen signal housing. Sophia saw a hand first, white with dust, then Zoey’s face. Her youngest sister had folded herself into the narrow triangle beneath the housing. The spiral mark at her throat flickered a weak silver-grey. Her eyes were open too wide.",
    "“I’m here,” Zoey whispered.",
    "Sophia crawled to her, ignored the sharp protest of her shoulder, and gripped her forearm. Whole. Warm. Shaking hard enough that Sophia could feel it in her own teeth.",
    "“I’ve got you.”",
    "Zoey looked past her. “The metal is crying.”",
    "“It is settling,” Kiera said. “Those are tension failures.”",
    "“No.” Zoey’s fingers locked around Sophia’s. “Not that. It’s scared.”",
    "Sophia almost told her not to be ridiculous. The command rose automatically—clean, sharp, useful. Then the platform groaned again, and the sound was not metal. It had a long, animal drag to it, as if the city were pulling breath through a crushed throat.",
    "Sophia swallowed the command.",
    "“Can you crawl?” she asked.",
    "Zoey nodded.",
    "“Good. Kiera, route.”",
    "Kiera’s mouth tightened at the familiar transfer of responsibility. Sophia saw it and did not apologize. There was no room for apologies while the platform was deciding whether to remain a platform.",
    "“Forward stairwell is gone. The service conduit is intact, if the lower brace is still attached.” Kiera pointed toward the dark. “It ascends to a maintenance junction. We need to cross the center span before the arrestors fail.”",
    "“Up?” Sophia asked.",
    "“Down is already flooding.”",
    "As if summoned by the word, black water began to spill through the broken lower level. It carried strips of insulation, a worker’s orange glove, and a chemical stink that made Sophia’s eyes water. The water did not spread like a leak. It rose in a smooth, deliberate line, filling the lowest troughs first.",
    "Sophia had seen this water’s work before. All her life, in fact—every corridor in the lower sectors wore its history on the walls. Flood marks notched into the stanchions, one groove per cycle, the newest ones bright steel where the rust hadn’t had time to close them. Tool brackets welded at intervals along the rails, and tools chained to the brackets—wrenches, bars, a coil of line hanging useless in the air—because the water came on schedule, and crews learned to chain down what they wanted to keep. A bell mounted in a junction box, painted yellow. Twenty minutes’ warning, the old hands said. The landlord’s knock.",
    "There was a bracket ten feet from Sophia’s hand. There was a chain. There was no tool. Someone had unclipped it in a hurry, or never came back to clip it again.",
    "“That isn’t runoff.” Kiera’s voice had gone flat with attention. She had dragged herself upright and was watching the water’s surface the way other people watched faces. “Runoff finds its own level. This is filling trough by trough. Someone is directing it.”",
    "“It’s sewage.”",
    "“It’s irrigation,” Kiera said. “They are watering the bottom of the city. On a schedule.”",
    "On the far wall, half-drowned already, a valve tag glinted where the paint had worn off. Sophia could not read it from this angle and could not get closer. But she remembered the ones posted outside the work decks: CYCLE TEN — 04:40 — CLEAR THE DECK. Like a timetable for a train no one was allowed to board. The city was not drowning them, she realized. The city was mopping its floor.",
    "They were the dirt.",
    "Kiera watched it for two beats. “A pressure gate opened below us.”",
    "“Because of the collapse?”",
    "“Maybe.” Kiera did not sound as if she believed it.",
    "Sophia helped Zoey free of the housing, then steadied Kiera when she put weight on her injured knee. They moved in a line across the slanted platform: Sophia first, because she could not bear to put either of them ahead of her; Kiera second, because she could read a surface before it failed; Zoey between their joined hands.",
    "The pack was still clipped to Sophia’s back. Two water canteens, four ration bars, thermal blankets, Kiera’s diagnostic slate. Not enough, but enough to turn panic into a plan. Halfway to the stairwell, a figure rose behind a buckled turnstile.",
    "He wore oilskin canvas and a respirator made from the bottom half of a kettle. A pry bar rested on one shoulder. He was thin in the way low-sector people became thin: not fragile, but sharpened by lack. His eyes passed over Sophia and settled on Kiera’s blue mark.",
    "“You three came off the upper line,” he said.",
    "“We came off a dead platform,” Kiera answered.",
    "The scavenger tilted his head toward her. “I asked the quiet one.”",
    "Kiera drew breath. Sophia stepped in front of her.",
    "“We’re passing through,” Sophia said.",
    "The man’s eyes shifted to the wrench tucked through the loop of her belt. “You answer for all of them?”",
    "“I answer first.”",
    "A small silence opened. Sophia felt Kiera stiffen behind her, not from fear. From insult. Sophia knew that tone in the muscles of her sister’s arm. She knew it and stayed in front of her anyway.",
    "“I can answer for myself,” Kiera said behind her. Quietly. For the scavenger’s benefit, or Sophia’s, or no one’s.",
    "“I know,” Sophia said, and did not move.",
    "She felt—more than heard—Kiera’s jaw set. It was an old geometry between them, drawn when they were too young to redraw it: Sophia was the wall, Kiera was the surveyor, and walls did not ask where to stand. The scavenger watched them both with the flat patience of a man waiting for metal to cool.",
    "The scavenger glanced at Zoey. “Fresh brands. Nexus will pay for fresh brands.”",
    "“Then go collect someone else.”",
    "“You don’t understand what you are.”",
    "“No,” Sophia said. “But I know what you’re doing.”",
    "The man’s grip shifted on the pry bar. He was not eager to fight. Neither was she. That did not make the space between them safer.",
    "A thin metallic crack sounded above them.",
    "Zoey stopped walking.",
    "“Sophia,” she said.",
    "Not loudly. Not with the panic Sophia expected. The word had the hard, flat quality of someone who had finally heard the shape of a disaster.",
    "Sophia looked back despite herself.",
    "Zoey was staring at an expansion joint twenty feet overhead. Fine grey dust sifted from it in a crooked stream.",
    "“We have to move now,” Zoey said. “Not the stairs. The tunnel on the right.”",
    "“The tunnel is partially collapsed,” Kiera said.",
    "“The stairs are worse.”",
    "Sophia looked from the safe-looking stairwell to the narrow maintenance tunnel choked with snapped conduit. Every instinct in her body wanted to choose for Zoey. To tell her that fear had made a picture out of noise. To take the route she could see.",
    "“Why?” she asked instead.",
    "Zoey’s gaze snapped to hers. Surprise showed first. Then terror. “Because it is going to fall.”",
    "The scavenger laughed once behind his mask.",
    "Sophia hated him for it. She hated the time it took to decide. She hated that Kiera was waiting for her decision rather than making one herself.",
    "“Right tunnel,” Sophia said.",
    "They ran.",
    "The scavenger shouted after them, perhaps a warning, perhaps a curse. The platform tilted as they reached the tunnel mouth. Sophia shoved Zoey through first, then caught Kiera at the waist when her bad knee buckled. The supply pack snagged on a twisted rail.",
    "There was no time to unhook it.",
    "Sophia tore free.",
    "The ceiling came down where they had been standing.",
    "The impact drove dust through the tunnel in a solid wall.",
    "Something struck Sophia’s back. She folded over Zoey, shielding her with both arms. The amber sigil flared so hot that the fabric at her sleeve smoked.",
    "When the noise stopped, the stairwell was gone.",
    "So was the pack.",
    "Kiera crawled to the edge of the new rubble slope, coughing into her sleeve. She looked at the buried shape of the pack without saying anything.",
    "Two canteens. Four ration bars. The slate. Gone beneath six feet of concrete.",
    "Sophia started to climb toward it.",
    "Kiera seized her jacket. “No.”",
    "“We need it.”",
    "“The deck is still moving.”",
    "“We need it.”",
    "“Then we should have listened sooner.”",
    "The words were quiet. That made them worse.",
    "“You did it again,” Kiera said.",
    "“Did what.”",
    "“Answered for me. He addressed me. He looked at me. And you stepped in front.” Kiera’s voice stayed low, careful around the blood at her knee. “I had an answer.”",
    "“I know you had an answer.”",
    "“You did not wait to hear it.”",
    "“There was a man with a pry bar and you were bleeding.” Sophia gestured at Kiera’s leg, then at the rubble where the pack had been. “Look where arguing got us.”",
    "“Arguing didn’t get us that.” Kiera looked at the rubble too. “Six seconds got us that. The six you spent deciding whether Zoey was right.”",
    "The words landed clean. Zoey, ten feet away, pressed herself smaller against the tunnel wall, watching them with an expression too old for her face. Sophia saw her watching and dropped her voice—which was its own kind of deciding, done for Zoey without Zoey.",
    "“I kept you alive this morning,” Sophia said. “I’m keeping you alive now. If you don’t like how I do it—”",
    "“That is not what it means.” Kiera tested her weight on the bad leg and did not flinch, or hid it well. “It means one day you will be wrong, and you will still be first.”",
    "She limped toward the tunnel mouth without waiting for the answer. That was the thing about Kiera: she never won the argument. She just kept it.",
    "Zoey waited for Sophia and took her hand and said nothing. Her palm was damp and cold. Sophia squeezed twice—the old code, I’ve got you—and Zoey squeezed back once, the old answer, I know.",
    "Zoey stood in the dust, one hand pressed to the silver spiral at her throat. “I’m sorry.”",
    "Sophia turned on her so quickly that Zoey flinched.",
    "The anger broke apart before it reached Sophia’s mouth.",
    "Zoey had warned them. Sophia had heard her. Sophia had still spent precious seconds deciding whether the warning deserved to be real.",
    "“It isn’t your fault,” Sophia said.",
    "Kiera let go of Sophia’s jacket. “The water is rising.”",
    "Below the rubble, black slurry lapped against the platform’s torn edge. It had already swallowed the exit they had used to descend from their work sector. Somewhere underneath it, the city’s lower gates were cycling shut.",
    "Sophia looked up the tunnel. It rose steeply, away from the flood and toward levels none of them had seen without a work permit.",
    "“Up,” she said.",
    "Kiera limped past her. “For the record, that was always the only route.”",
    "Sophia wanted to tell her she knew. Instead, she took Zoey’s hand and followed.",
    "The city had taken their water, their food, and the map that might have explained any of this. It had left them one direction.",
    "Sophia would keep her sisters alive. She could feel that certainty settle into her as heavily as the dust on her skin. She did not yet understand how much of them she might have to decide away to do it.",
  ],
};